---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
