---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
  namespace: default
spec:
  storageClassName: media
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.157
    path: '/mnt/block1/Plex/Plex'
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media
  resources:
    requests:
      storage: 1Mi
