---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-monica-pv
  namespace: home
spec:
  storageClassName: media
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDRESS}
    path: '/mnt/block1/Plex/services/monica'
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-monica-pvc
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media
  resources:
    requests:
      storage: 1Mi
