# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:peMShcslzoXS+xQirVw7738=,iv:6UMX200Tmupv0q/3rdFZXjlsXFjiaghs/fc9n9p7Us8=,tag:9c+cUgJVNuqwP5h+iKp4TA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:VVvkFFGeL6ZF96r/Cox+Bcbb,iv:WddXr2Vz46QM0fwoeNUp7AFPI5w26QetNWEOGnHsPZU=,tag:yW8x5lV6dlFNeLPTiBltSw==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:ylmYJEOBX9mgx7bpJDY=,iv:to/MRIQiRTfwWNqXcdVzkSBl2YvGa3+CzsJfXExhVHY=,tag:E4JGsQdBY45c4ISeT1KxVQ==,type:str]
    SETTING_TZ: ENC[AES256_GCM,data:ub3lhKn3J375RNJouaY=,iv:PwsdG29tvcRM0Ps87dNB2c9ya+wLcQtfGaAhbyqxoK0=,tag:W4Me/10Pb9PrSu+/k3Sgbg==,type:str]
    DEBUG_INTERVAL: ENC[AES256_GCM,data:YQQ=,iv:1EqTH1kGBT9Q/DAvlk7MjTrc9RXEph7CPhxatJyrVu8=,tag:cEE5iz3F213vPZfAKXAHbA==,type:str]
    STANDARD_INTERVAL: ENC[AES256_GCM,data:Yl4=,iv:NMEDUC0pWVyGbssOlfit+HCMWsbCPnwb/YKDgtgPhP0=,tag:Z8D4zYe9rB56JGZR5TwCzQ==,type:str]
    PLEX_CLAIM: ENC[AES256_GCM,data:YzEzBt+dcOAGBzbV4IP7EWfq5SZ/rtSvgtY=,iv:bJU0Wlcp53AV7ZQtIu3zan/cDKWmOW3+smscpjgmEVQ=,tag:A4e35dk5ATzZLkb3teqxiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mjcfm2evr255u5ekkw2tl565wc9xl0m04956geh6uhkuz6zhxycqd27d78
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTm4xUVZVUDc3OWpLYm1E
            VG0yczJtV1doZjhPdWlldElhUlNFTit3TVYwCjBxTG1DVStPd1VOL2dBWU5UNGtH
            Qmljam85QWkvY0Z4NnowY0hlNkxGMGcKLS0tIFQxY1ZpY29QRzA2WEF3TVR3K1Yr
            SWIrcTIwY290VGpXT2d5VUIxZjVsR28K3MIwEYIm4tzTRr5C0SpDhK9fss5FcALc
            qcxZe3DUVMg0wjSRiaR19NFTSIyRVYHmulH0tke99uNeBupfj7zbtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-24T13:54:23Z"
    mac: ENC[AES256_GCM,data:FAaKdWpzGExOhaHSGRVsPOKn1X+oMCgnoF/vQdmQJ/07t/hwfvpQcjSfv1iPreKfMo1jtPtLpMjcXMJDk9THR/w3+ImJLn+41ZNLWfXMj16I0pWFYODaIGe6EX3L+ij8JSFRn9Q9TksW5OQ5EGroZqdrEyg9wQEY4wGEHIwT6MQ=,iv:kmnh5VJwdSt4au3FL7tKA+iIITO6HYsABzDGsHvXDR8=,tag:+u2TeIiFhYkNQula/a5FrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
