# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:peMShcslzoXS+xQirVw7738=,iv:6UMX200Tmupv0q/3rdFZXjlsXFjiaghs/fc9n9p7Us8=,tag:9c+cUgJVNuqwP5h+iKp4TA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:VVvkFFGeL6ZF96r/Cox+Bcbb,iv:WddXr2Vz46QM0fwoeNUp7AFPI5w26QetNWEOGnHsPZU=,tag:yW8x5lV6dlFNeLPTiBltSw==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:ylmYJEOBX9mgx7bpJDY=,iv:to/MRIQiRTfwWNqXcdVzkSBl2YvGa3+CzsJfXExhVHY=,tag:E4JGsQdBY45c4ISeT1KxVQ==,type:str]
    SETTING_TZ: ENC[AES256_GCM,data:ub3lhKn3J375RNJouaY=,iv:PwsdG29tvcRM0Ps87dNB2c9ya+wLcQtfGaAhbyqxoK0=,tag:W4Me/10Pb9PrSu+/k3Sgbg==,type:str]
    DEBUG_INTERVAL: ENC[AES256_GCM,data:YQQ=,iv:1EqTH1kGBT9Q/DAvlk7MjTrc9RXEph7CPhxatJyrVu8=,tag:cEE5iz3F213vPZfAKXAHbA==,type:str]
    STANDARD_INTERVAL: ENC[AES256_GCM,data:Yl4=,iv:NMEDUC0pWVyGbssOlfit+HCMWsbCPnwb/YKDgtgPhP0=,tag:Z8D4zYe9rB56JGZR5TwCzQ==,type:str]
    PLEX_CLAIM: ENC[AES256_GCM,data:P6OG8QkPAgEhpswYboqz+6GKbTKLL7mG800=,iv:siRDeAtlFfzsMD6xcjJAN0mKiNPTOkQ5hrnghplPBQM=,tag:KKRyejzPh6LSeYaFb44a+Q==,type:str]
    NAS_ADDRESS: ENC[AES256_GCM,data:YmatQ1uA/AKXE7bjaw==,iv:mr2ngXRy75U78iPy05H7j88QHkDiIaBVxkqGHKxPyJc=,tag:GBlND3gdZWh4Jju7k/J1UQ==,type:str]
    NETWORK_SUBNET: ENC[AES256_GCM,data:mYMXuQ9c8h1SGeBPaKg=,iv:e+OVs3yZ6ZNyYc7DD5BfFlc3pFuoynWnGNpUfRr0Cq8=,tag:16o+1jKAZ3TY3uPbRQ0TqA==,type:str]
    LB_PLEX_IP: ENC[AES256_GCM,data:BQkTExS0yr1wq6GVT4w=,iv:sH4rYoROWtCizSf3V/uTyJ5XGyccn/+vORVpX2/uhqA=,tag:Xz0YP7Ii0WXuvYdVLf64Jg==,type:str]
    MONICA_DB_PASSWORD: ENC[AES256_GCM,data:GmmYGFLH4FZScyiE,iv:7ZD8NSlShEQOmvIf8OrwBvBZfK0QpTeANdfKPfoXYrU=,tag:O754Sg0qCch4/yQNolR63g==,type:str]
    MONICA_APP_KEY: ENC[AES256_GCM,data:JaTUJndkAHOVVFEYXEYjdBdO4429dHWiTg8OLnbwdGM=,iv:+02YzvGLaoF0ubuM8k+5vGEA+QPRggkexeRkIfGhPck=,tag:kQMynMDC6AypcCTGeCv1HA==,type:str]
    SECRET_EMAIL_USERNAME: ENC[AES256_GCM,data:kbpE/XfXL3MUCbkuBisLOmf1JjiRU3p6vQ==,iv:oM929FXrZS4QAEEoA3Ryytvr/QgO7PP+XR23j4EOCyE=,tag:DbylmjH7P++JcQVr2anHtg==,type:str]
    SECRET_EMAIL_PASSWORD: ENC[AES256_GCM,data:m30nZNxXHfo=,iv:jqx5k3U7edgWfG6xkLOc7oWsQezzF6pBOyKTVxoK44c=,tag:dqQWDzkwIV0yIGoF3GPVWg==,type:str]
    MONICA_MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:QikENSoQi9nnRmUjhIPtWtfanJwBokoTnOb7pPjyrVATt6ZUgZU=,iv:0FR+8+dV59KC9+SB1YFd2ji+J2MHZspzHvfn/soG19s=,tag:lcNXjZOURRdxT6cz9hsgEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mjcfm2evr255u5ekkw2tl565wc9xl0m04956geh6uhkuz6zhxycqd27d78
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTm4xUVZVUDc3OWpLYm1E
            VG0yczJtV1doZjhPdWlldElhUlNFTit3TVYwCjBxTG1DVStPd1VOL2dBWU5UNGtH
            Qmljam85QWkvY0Z4NnowY0hlNkxGMGcKLS0tIFQxY1ZpY29QRzA2WEF3TVR3K1Yr
            SWIrcTIwY290VGpXT2d5VUIxZjVsR28K3MIwEYIm4tzTRr5C0SpDhK9fss5FcALc
            qcxZe3DUVMg0wjSRiaR19NFTSIyRVYHmulH0tke99uNeBupfj7zbtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-05T13:08:07Z"
    mac: ENC[AES256_GCM,data:A0z5i4ApWzwJfrqJtkrri+gz2OfcpuvIxrRziiVL4N4BxgfYhs5FSMTktX+5zKQdAwhGflxAGDoYAg5WzBzkQfGJ0dbzX+4NaQU5bAuhVcsWkKwcO8ZEZfNJ4mEPkTNFf4B4pGT01nn5qYCIBZ1p6l/oKjgiKRwY1V5emQxD6/c=,iv:n/OZgvU4ow4tabdnUUgHl7Y2/8bwoR99YrdWfk3vQRg=,tag:aCHI3i/XNP4BJDGFqaZUBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
