---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octoprint-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  reclaimPolicy: Retain
  resources:
    requests:
      storage: 5Gi
