---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: octoprint
  namespace: default
spec:
  interval: ${DEBUG_INTERVAL}
  chart:
    spec:
      chart: octoprint
      version: 1.7.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: ${DEBUG_INTERVAL}
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: octoprint/octoprint
      tag: 1.6.1
      pullPolicy: IfNotPresent
    env:
      TZ: 'America/Denver'
      OCTOPRINT_PORT: 5000
    ingress:
      main:
        enabled: true
        ingressClassName: 'traefik'
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt-production'
          traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
          hajimari.io/enable: 'true'
          hajimari.io/icon: printer-3d-nozzle
        hosts:
          - host: 'octoprint.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'octoprint.${SECRET_DOMAIN}'
            secretName: 'octoprint-tls'
    securityContext:
      # -- (bool) Privileged securityContext may be required if USB devics are accessed directly through the host machine
      privileged: true
    persistence:
      data:
        enabled: true
        existingClaim: octoprint-data
        mountPath: /octoprint/octoprint
      printer:
        enabled: false
        type: hostPath
        hostPath: /dev/ttyUSB0
    podAnnotations:
      configmap.reloader.stakater.com/reload: 'octoprint-data'
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
