---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: octoprint
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: octoprint
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: octoprint/octoprint
      tag: 1.6.1
    env:
      TZ: 'America/Denver'
    ingress:
      main:
        enabled: true
        ingressClassName: 'traefik'
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt-production'
          traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
        hosts:
          - host: 'octoprint.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'octoprint.${SECRET_DOMAIN}'
            secretName: 'octoprint-tls'
    persistence:
      data:
        enabled: true
        existingClaim: octoprint-data
      printer: '/dev/ttyUSB0'
    podAnnotations:
      configmap.reloader.stakater.com/reload: 'octoprint-data'
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
