---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
  labels:
    kustomize.toolkit.fluxcd.io/substitute: 'disabled'
spec:
  interval: ${DEBUG_INTERVAL}
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.16
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-charts
        namespace: flux-system
      interval: ${DEBUG_INTERVAL}
  values:
    replicaCount: 1
    nfs:
      server: ${NAS_ADDRESS}
      path: '/mnt/block1/Plex'
      mountOptions:
        - noatime
        - nodiratime
        - nfsvers=4.1
    storageClass:
      defaultClass: false
      pathPattern: '${.PVC.namespace}-${.PVC.name}'
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nfs-subdir-external-provisioner
              topologyKey: kubernetes.io/hostname
