apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - artifacts.yaml
  - cert-manager.yaml
  - home.yaml
  - media.yaml
  - metallb-system.yaml
  - networking.yaml
  - observability.yaml
