---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hajimari-config-pv
  namespace: default
spec:
  storageClassName: local
  capacity:
    storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /local-path/hajimari-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: hajimari-config-pv
  resources:
    requests:
      storage: 128Mi
